In [1]:
import os
from llama_index import SimpleDirectoryReader
from langchain.document_loaders import DirectoryLoader
from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.vectorstores import FAISS

C:\Users\WC335VY\Anaconda3\lib\site-packages\requests\__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.8) or chardet (5.1.0)/charset_normalizer (2.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
Could not import azure.core python package.


In [2]:
# os.environ['OPENAI_API_KEY'] = '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'
os.environ['OPENAI_API_KEY'] = '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'

# path = 'All'
path = 'UL_Docs'

In [3]:
# loader = SimpleDirectoryReader(path)
# documents = loader.load_data()
# documents = [doc.to_langchain_format() for doc in documents]

In [13]:
# !pip install unstructured==0.6.10
# !pip install pdf2image==1.16.3
!pip install tabulate==0.9.0

In [ ]:
print("===>")
# loader = DirectoryLoader('../', glob="**/*.md")
loader = DirectoryLoader('UL_Docs', glob="**/*.pdf")
documents = loader.load()
print("--",documents)
# for doc in documents:
#     print(doc)

In [18]:
documents = [doc.to_langchain_format() for doc in documents]
# print(documents)

AttributeError: 'Document' object has no attribute 'to_langchain_format'

In [ ]:


# print("documents=>>>",documents[0].metadata)
text_splitter1 = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=100)
docs1 = text_splitter1.split_documents(documents)
print("docs1===>", docs1)

text_splitter2 = RecursiveCharacterTextSplitter(chunk_size=800, chunk_overlap=100)
docs2 = text_splitter2.split_documents(documents)


# docs_index_v1 chunksize 500 overlap 100
# docs_index_v2 chunksize 800 overlap 100
embeddings = OpenAIEmbeddings()

# docsearch1 = Chroma.from_texts(docs1, embeddings, metadatas=[{"source": str(i)} for i in range(len(docs1))])
# docsearch2 = Chroma.from_texts(docs2, embeddings, metadatas=[{"source": str(i)} for i in range(len(docs2))])

# metadatas=[{"source": str(i)} for i in docs1]
# print("metadatas",metadatas)

db1 = FAISS.from_documents(docs1, embeddings  )
db1.save_local(path+"_v1")

db2 = FAISS.from_documents(docs2, embeddings )
db2.save_local(path+"_v2")

In [22]:
import numpy as np
X = np.arange(12).reshape(3,4)

In [23]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
X.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [26]:
# d,r,c

X.T.max(axis=0)

array([ 3,  7, 11])

In [27]:
[i.min() for i in X]

[0, 4, 8]

In [28]:
X.sum() 

66

In [30]:
arr = 2*np.arange(0,2,0.5)

In [31]:
if arr <= 0.6:
    print ("condition satisfies")
else:
    print ("condition doesn't satisfy") 

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [32]:
x = np.ones((5,5))

In [33]:
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [35]:
x[1:-1,1:-1] = 0

In [36]:
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [48]:
arr1 = np.array([1,2,3,6,3,2]) 

arr2 = np.array([4,2,1,3,3,2]) 

arr3 = np.zeros(len(arr1)) 

In [43]:
# for i in range(len(arr1)): 
#     arr3[i] = arr1[i] * arr2[i] 

# arr3 = arr1*arr2 

for i in range(len(arr1)): 
    if(arr1[i] < 0 ): 
        arr1[i] = -1 
    else: 
        arr1[i] = 1

In [44]:
arr3

array([ 4,  4,  3, 18,  9,  4])

In [45]:
arr1

array([1, 1, 1, 1, 1, 1])

In [49]:
np.where(arr1 > 0, 1, -1) 


array([1, 1, 1, 1, 1, 1])

In [50]:
arr1

array([1, 2, 3, 6, 3, 2])

In [56]:
np.arange(18).reshape(2,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [65]:
np.random.randint(5,10)

7

In [64]:
np.random.rand(5,10)

array([[0.02462642, 0.62519048, 0.01301977, 0.99751865, 0.05334239,
        0.33854885, 0.72616038, 0.76330138, 0.59865818, 0.83829272],
       [0.31156637, 0.97551494, 0.25138989, 0.68516257, 0.56626284,
        0.97550426, 0.88931525, 0.58874945, 0.68349701, 0.84659615],
       [0.72878289, 0.81030635, 0.66397544, 0.41801985, 0.16725727,
        0.58216077, 0.72544748, 0.399066  , 0.41259259, 0.69247348],
       [0.09733849, 0.20678799, 0.42013681, 0.67693505, 0.06031267,
        0.72759768, 0.03830595, 0.14425704, 0.24207844, 0.17294473],
       [0.6000198 , 0.98724772, 0.53762403, 0.99414347, 0.28080042,
        0.42562097, 0.55868329, 0.02454755, 0.24768018, 0.61975388]])

In [68]:
arr = np.arange(10)
np.split(arr, 3)

ValueError: array split does not result in an equal division

In [70]:
arr = np.arange(10)
np.split(arr, 5)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [69]:
arr = np.arange(10)
np.split(arr, [2,5])

[array([0, 1]), array([2, 3, 4]), array([5, 6, 7, 8, 9])]

In [71]:
arr = np.arange(10)
np.split(arr, [5, 12])

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([], dtype=int32)]